[package]
name = "wavetable_synthesizer"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["advanced"] }
rodio = "0.19"
strum_macros = "0.26.4"
iced_widget = { version = "0.12.3", features = ["canvas"] }